#!/bin/bash 

PASSWORD="/root/.ethereum/password"

if [ ! -f "${PASSWORD}" ]
then
  pwgen -1 >"${PASSWORD}"
fi

if [[ $(geth --rinkeby account list | wc -l) -lt 1 ]];
then
  geth --rinkeby account new --password "${PASSWORD}"
fi


geth --rinkeby \
     --syncmode fast \
     --password "${PASSWORD}" \
     --rpc \
     --rpcapi 'net,web3,eth,debug' \
     --networkid=4 \
     --rpcaddr="0.0.0.0" \
     --rpccorsdomain "*"
#geth --testnet --password $PASSWORD 


